steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=app/secret/service_user.json.enc
  - --plaintext-file=app/secret/service_user.json
  - --location=global
  - --keyring=testtube
  - --key=testtube
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=helm/app/values.yaml.enc
  - --plaintext-file=helm/app/values.yaml
  - --location=global
  - --keyring=testtube
  - --key=testtube
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app', '.']
  dir: 'app'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx', '.']
  dir: 'nginx'


images: ['gcr.io/$PROJECT_ID/app', 'gcr.io/$PROJECT_ID/nginx']
timeout: 600s
